# Generated by Django 4.0.5 on 2022-07-05 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('run', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technician',
            name='name',
        ),
        migrations.AddField(
            model_name='technician',
            name='tech',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='run.person'),
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasks', models.ManyToManyField(to='run.task')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='run.technician')),
                ('tools', models.ManyToManyField(to='run.tools')),
            ],
        ),
    ]
