# Generated by Django 4.0.5 on 2022-07-07 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('run', '0002_remove_technician_name_technician_tech_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technician',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
